INSERT INTO public.accounting_competence_data (
  unit_id,
  ano,
  mes,
  total_folha,
  encargos,
  prolabore,
  num_funcionarios,
  das_valor,
  das_vencimento,
  darf_valor,
  darf_vencimento,
  gps_valor,
  gps_vencimento,
  inss_valor,
  inss_vencimento,
  fgts_valor,
  fgts_vencimento,
  iss_valor,
  iss_vencimento,
  receita_servicos,
  receita_outras,
  receita_observacoes,
  status
) VALUES (
  '0e8ad4c3-a018-42ef-8941-9cd7e3e1611d',
  2026,
  1,
  45000.00,
  12500.00,
  8000.00,
  12,
  3500.00,
  '2026-01-20',
  1200.00,
  '2026-01-25',
  850.00,
  '2026-01-15',
  2100.00,
  '2026-01-20',
  3600.00,
  '2026-01-07',
  1500.00,
  '2026-01-10',
  185000.00,
  12500.00,
  'Receitas de exames laboratoriais e convênios',
  'informado'
) ON CONFLICT (unit_id, ano, mes) DO UPDATE SET
  total_folha = EXCLUDED.total_folha,
  encargos = EXCLUDED.encargos,
  prolabore = EXCLUDED.prolabore,
  num_funcionarios = EXCLUDED.num_funcionarios,
  das_valor = EXCLUDED.das_valor,
  das_vencimento = EXCLUDED.das_vencimento,
  darf_valor = EXCLUDED.darf_valor,
  darf_vencimento = EXCLUDED.darf_vencimento,
  gps_valor = EXCLUDED.gps_valor,
  gps_vencimento = EXCLUDED.gps_vencimento,
  inss_valor = EXCLUDED.inss_valor,
  inss_vencimento = EXCLUDED.inss_vencimento,
  fgts_valor = EXCLUDED.fgts_valor,
  fgts_vencimento = EXCLUDED.fgts_vencimento,
  iss_valor = EXCLUDED.iss_valor,
  iss_vencimento = EXCLUDED.iss_vencimento,
  receita_servicos = EXCLUDED.receita_servicos,
  receita_outras = EXCLUDED.receita_outras,
  receita_observacoes = EXCLUDED.receita_observacoes,
  status = EXCLUDED.status,
  updated_at = now();